name: Issue6_Deploy

on: [workflow_dispatch]

env:
  baselineResourceGroup: ghgovenv
  baselineVariableStorageAccountName: ghgovenvnotsecrets
  baselineVariableTableName: pipelinevariables
  baselineTablePartitionKey: totestvariables

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore "Code To Push To Environments/App Service Web App/DevAppSample.sln"
    - name: Build
      run: dotnet build --configuration Release --no-restore "Code To Push To Environments/App Service Web App/DevAppSample.sln"

    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{secrets.PF_AZURE_CREDENTIALS}}
        
    - name: Get Storage Account Key Info
      run: |
        echo ::set-env name=STORAGE_KEY::$(az storage account keys list -g $baselineResourceGroup -n $baselineVariableStorageAccountName --query "[0].{value:value}" -o tsv)
        echo ::set-env name=CONNECTION_STRING::'DefaultEndpointsProtocol=https;AccountName='$baselineVariableStorageAccountName';AccountKey='$STORAGE_KEY';EndpointSuffix=core.windows.net'
    
    - name: Get Pipeline Variables
      run: |
        echo ::set-env name=RESOURCEGROUPNAME::$(az storage entity show --connection-string $CONNECTION_STRING --table-name $baselineVariableTableName --partition-key $baselineTablePartitionKey --row-key resourcegroupname --select Content --query "Content" -o tsv)
        echo ::set-env name=LOCATION::$(az storage entity show --connection-string $CONNECTION_STRING --table-name $baselineVariableTableName --partition-key $baselineTablePartitionKey --row-key location --select Content --query "Content" -o tsv)
        echo ::set-env name=APPSERVICEPLANNAME::$(az storage entity show --connection-string $CONNECTION_STRING --table-name $baselineVariableTableName --partition-key $baselineTablePartitionKey --row-key appserviceplanname --select Content --query "Content" -o tsv)
       
    - name: Show Pipeline Variables
      run: | 
        echo "Partition key:" $baselineTablePartitionKey
        echo "Resource group:" $RESOURCEGROUPNAME
        echo "Location:" $LOCATION 
        echo "App Service Plan Name:" $APPSERVICEPLANNAME 
      

      

